### ISSUE TITLE
The result of reference_adain seems not well?

### ISSUE THREAD

**Issue by Eric07110904** [SerialLain3170/Colorization#34]
@SerialLain3170 
Sorry, my english is poor.
I train a reference_adain model (15 epochs),  and test it using Adeliene GUI.
**However,  In testing stage, the generated result looks very strange.** 
What should I do to achieve to a better result?(**still training to 100 epochs?**)

- Generation (**using testing data**)

![image](https://user-images.githubusercontent.com/42273490/165472989-47579070-1e79-4a5e-971d-5bf13c46bc28.png)

- Generation (**using training data**)

![image](https://user-images.githubusercontent.com/42273490/165491852-89e8f45f-e493-45e6-8158-5003c9c0db99.png)

- Visualization of validation 

![image](https://user-images.githubusercontent.com/42273490/165485071-5f7da56f-24d0-4b7a-a043-98d6703a697c.png)

**Comment by SerialLain3170** [comment]
Thank you for the report.

The trained `reference_adain` model usually fails to colorize if the poses of the input and the reference are different. Judging from the validation results, the training have gone well, so I think that your trained model would succeed in colorization if the poses of the input and the reference are similar. 

If you would like to colorize difficult cases, I recommend that you use `reference_scft` instead of `reference_adain` because `reference_scft` is able to colorize the cases that `reference_adain` fails to colorize like the [results](https://github.com/SerialLain3170/Colorization/tree/master/reference_scft). I am sorry for the inconvenience.

**Comment by Eric07110904** [comment]
> Thank you for the report.
> 
> The trained `reference_adain` model usually fails to colorize if the poses of the input and the reference are different. Judging from the validation results, the training have gone well, so I think that your trained model would succeed in colorization if the poses of the input and the reference are similar.
> 
> If you would like to colorize difficult cases, I recommend that you use `reference_scft` instead of `reference_adain` because `reference_scft` is able to colorize the cases that `reference_adain` fails to colorize like the [results](https://github.com/SerialLain3170/Colorization/tree/master/reference_scft). I am sorry for the inconvenience.

@SerialLain3170 
Very thank yor for the response.
Actually I allready trained a `reference_scft` model using same dataset(14000 pair), **but the result looks strange**.
I only change the `param.yaml`, and following picture is validation result.
```yaml
train:
    epoch: 1000
    snapshot_interval: 10000
    batchsize: 3
    validsize: 3

dataset:
    extension: ".png"
    train_size: 256
    valid_size: 384
    color_space: "rgb"
    line_space: "rgb"
    line_method: ["xdog", "pencil", "blend"]
    src_perturbation: 0.5
    tgt_perturbation: 0.2
```

- **40000 Iterations**

![image](https://user-images.githubusercontent.com/42273490/165524641-108a7472-9b50-4cbd-a591-871ee409af99.png)

- **120000 Iterations**

![image](https://user-images.githubusercontent.com/42273490/165524909-8117ceef-7195-4e12-b4db-423c15918477.png)

The result of validation looks has same color style, i don't know whether this condition is normal.
Do you have any opinion about this condition? 
Thank you!

**Comment by SerialLain3170** [comment]
I think that the problem may come from the scale in [random_crop](https://github.com/SerialLain3170/Colorization/blob/master/reference_scft/dataset.py#L100). If you set `dataset.train_size` 256,  I recommend that you set the scale from 288 to 384 instead of 384 to 512. Since the scale is hard coded, I am sorry for the inconvenience.

**Comment by Eric07110904** [comment]
> I think that the problem may come from the scale in [random_crop](https://github.com/SerialLain3170/Colorization/blob/master/reference_scft/dataset.py#L100). If you set `dataset.train_size` 256, I recommend that you set the scale from 288 to 384 instead of 384 to 512. Since the scale is hard coded, I am sorry for the inconvenience.

Thank you for your reply.
I use default configuration about `param.yaml` now, **but the problem still exist.**
```yaml
train:
    epoch: 1000
    snapshot_interval: 2000
    batchsize: 2
    validsize: 3

dataset:
    extension: ".png"
    train_size: 384
    valid_size: 512
    color_space: "rgb"
    line_space: "rgb"
    line_method: ["xdog", "pencil", "blend"]
    src_perturbation: 0.5
    tgt_perturbation: 0.2
```
```python
@staticmethod
def _random_crop(line: np.array,
    color: np.array,
    size: int) -> (np.array, np.array):
    scale = np.random.randint(396, 512)
```

- My dataset: https://www.kaggle.com/datasets/ktaebum/anime-sketch-colorization-pair
Image:  3 x 512 x 512 
Sketch: 3 x 512 x 512

- Validation result (14000 iterations)

![image](https://user-images.githubusercontent.com/42273490/165655024-689aa35a-dd7b-4d40-8cfa-624c03660955.png)

- Validation result (3epochs, 14000 iterations)

![image](https://user-images.githubusercontent.com/42273490/165655064-967bc833-6710-4844-80ec-e9581aab6b65.png)

Is the validation result normal in few epochs?
